module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      PoppinsBlack: ["PoppinsBlack", "sans-serif"],
      PoppinsBold: ["PoppinsBold", "sans-serif"],
      PoppinsExtraBold: ["PoppinsExtraBold", "sans-serif"],
      PoppinsExtraLight: ["PoppinsExtraLight", "sans-serif"],
      PoppinsLight: ["PoppinsLight", "sans-serif"],
      PoppinsMedium: ["PoppinsMedium", "sans-serif"],
      PoppinsRegular: ["PoppinsRegular", "sans-serif"],
      PoppinsSemiBold: ["PoppinsSemiBold", "sans-serif"],
      PoppinsThin: ["PoppinsThin", "sans-serif"],
    },
    extend: {
      colors: {
        primaryBg: "#4a88d8",
        secondaryBg: "#f5b20b",
        tertiaryBg: "#ca9d2c",
        sidebarBg: "#243d5c",
        sidebarHover: "#133259",
        paperRoot: "#ffffff",
        paperPrimary: "#f3efec",
        paperSecondary: "#e3ddd8",
        paperTertiary: "#887f78",
        primaryText: "#243d5c",
        secondaryText: "#000000",
        tertiaryText: "#ca9d2c",
        hintText: "#f28925",
        error: "#f22435",
        success: "#4bb543",
        inverse: "#ffffff",
        rootHover: "#fff6df",
        landingSecondaryBg: "#FDF0CE",
        landingShapeGreen: "#6BDBBE",
        landingShapePurple: "#6351C3",
      },
    },
  },
  plugins: [],
};
